from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from examplecywebserviceapp.serviceappmodel.base_model import Model
from examplecywebserviceapp import util


class CyRequestId(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None):  # noqa: E501
        """CyRequestId - a model defined in OpenAPI

        :param id: The id of this CyRequestId.  # noqa: E501
        :type id: str
        """
        self.openapi_types = {
            'id': str
        }

        self.attribute_map = {
            'id': 'id'
        }

        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'CyRequestId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CyRequestId of this CyRequestId.  # noqa: E501
        :rtype: CyRequestId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this CyRequestId.

        Id of Cytoscape Service-App REST Request  # noqa: E501

        :return: The id of this CyRequestId.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this CyRequestId.

        Id of Cytoscape Service-App REST Request  # noqa: E501

        :param id: The id of this CyRequestId.
        :type id: str
        """

        self._id = id
