from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from examplecywebserviceapp.serviceappmodel.base_model import Model
from examplecywebserviceapp import util


class CyServerStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, version=None):  # noqa: E501
        """CyServerStatus - a model defined in OpenAPI

        :param status: The status of this CyServerStatus.  # noqa: E501
        :type status: str
        :param version: The version of this CyServerStatus.  # noqa: E501
        :type version: str
        """
        self.openapi_types = {
            'status': str,
            'version': str
        }

        self.attribute_map = {
            'status': 'status',
            'version': 'version'
        }

        self._status = status
        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'CyServerStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CyServerStatus of this CyServerStatus.  # noqa: E501
        :rtype: CyServerStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this CyServerStatus.

        Status of server  # noqa: E501

        :return: The status of this CyServerStatus.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this CyServerStatus.

        Status of server  # noqa: E501

        :param status: The status of this CyServerStatus.
        :type status: str
        """
        allowed_values = ["ok", "error"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def version(self) -> str:
        """Gets the version of this CyServerStatus.

        Gets version of this service  # noqa: E501

        :return: The version of this CyServerStatus.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this CyServerStatus.

        Gets version of this service  # noqa: E501

        :param version: The version of this CyServerStatus.
        :type version: str
        """

        self._version = version
