from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from examplecywebserviceapp.serviceappmodel.base_model import Model
from examplecywebserviceapp.serviceappmodel.cy_web_menu_item_path import CyWebMenuItemPath
from examplecywebserviceapp import util

from examplecywebserviceapp.serviceappmodel.cy_web_menu_item_path import CyWebMenuItemPath  # noqa: E501

class CyWebMenuItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, root=None, path=None):  # noqa: E501
        """CyWebMenuItem - a model defined in OpenAPI

        :param root: The root of this CyWebMenuItem.  # noqa: E501
        :type root: str
        :param path: The path of this CyWebMenuItem.  # noqa: E501
        :type path: List[CyWebMenuItemPath]
        """
        self.openapi_types = {
            'root': str,
            'path': List[CyWebMenuItemPath]
        }

        self.attribute_map = {
            'root': 'root',
            'path': 'path'
        }

        self._root = root
        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'CyWebMenuItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CyWebMenuItem of this CyWebMenuItem.  # noqa: E501
        :rtype: CyWebMenuItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def root(self) -> str:
        """Gets the root of this CyWebMenuItem.

        Top level menu to place this service  # noqa: E501

        :return: The root of this CyWebMenuItem.
        :rtype: str
        """
        return self._root

    @root.setter
    def root(self, root: str):
        """Sets the root of this CyWebMenuItem.

        Top level menu to place this service  # noqa: E501

        :param root: The root of this CyWebMenuItem.
        :type root: str
        """

        self._root = root

    @property
    def path(self) -> List[CyWebMenuItemPath]:
        """Gets the path of this CyWebMenuItem.

        Service menu path and name  # noqa: E501

        :return: The path of this CyWebMenuItem.
        :rtype: List[CyWebMenuItemPath]
        """
        return self._path

    @path.setter
    def path(self, path: List[CyWebMenuItemPath]):
        """Sets the path of this CyWebMenuItem.

        Service menu path and name  # noqa: E501

        :param path: The path of this CyWebMenuItem.
        :type path: List[CyWebMenuItemPath]
        """

        self._path = path
